# Generated by Django 4.2.8 on 2026-05-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=16)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_tbl',
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('gender_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genders_tbl',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_tbl',
            },
        ),
        migrations.CreateModel(
            name='Product_Gender',
            fields=[
                ('product_gender_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_gender', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_gender_tbl',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=64)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.genders')),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=16)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(default='profile_pics/default_profile_pic.png', upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),    
            ],
            options={
                'db_table': 'users_tbl',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=128)),
                ('product_brand', models.CharField(max_length=128)),
                ('product_image', models.ImageField(upload_to='product_img/')),
                ('product_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.product_gender')),
                ('product_price', models.IntegerField(default=0)),
                ('product_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_tbl',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.payment')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.products')),
                ('quantity', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'history_tbl',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
                ('product_price', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cart_tbl',
            },
        ),
    ]
