# Generated by Django 4.2.8 on 2026-05-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
        sql="""
            ALTER TABLE cart_tbl 
            ADD COLUMN product_size_id BIGINT NOT NULL AFTER product_name_id,
            ADD CONSTRAINT fk_cart_product_size 
            FOREIGN KEY (product_size_id) 
            REFERENCES product_size_tbl(product_size_id) 
            ON DELETE CASCADE;
        """,
        reverse_sql="""
            ALTER TABLE cart_tbl 
            DROP FOREIGN KEY fk_cart_product_size,
            DROP COLUMN product_size_id;
        """
        ),
    ]
