# Generated by Django 4.2.8 on 2026-05-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20260520_0951'),
    ]

    operations = [
          migrations.RunSQL(
            sql="ALTER TABLE history_tbl ADD COLUMN product_total INTEGER(20) NULL AFTER product_price",
            reverse_sql="ALTER TABLE history_tbl DROP COLUMN product_total"
        ),
    ]
